# Generated by Django 4.1.6 on 2023-03-02 11:11

from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations, models
import django.db.models.deletion


def create_admin_user(apps, schema_editor):
    try:
        User.objects.get(username="admin")
    except User.DoesNotExist:
        User.objects.create_superuser("admin", "admin@example.com", "admin1234")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_number', models.CharField(max_length=40)),
                ('country_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(max_length=100)),
                ('rock_groups', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='climbing_website.country')),
            ],
        ),
        migrations.CreateModel(
            name='Rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rock_name', models.CharField(max_length=100)),
                ('photo_map', models.ImageField(upload_to='images/')),
                ('height', models.IntegerField()),
                ('insolation', models.IntegerField()),
                ('formation', models.IntegerField()),
                ('localization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rocks', to='climbing_website.localization')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rout_name', models.CharField(max_length=100)),
                ('grades', models.CharField(max_length=5)),
                ('autor', models.CharField(max_length=100)),
                ('number_of_glued', models.IntegerField()),
                ('trad', models.BooleanField()),
                ('description', models.CharField(max_length=250)),
                ('rock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='climbing_website.rock')),
            ],
        ),
        migrations.CreateModel(
            name='RouteGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RouteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_description', models.CharField(max_length=250)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='climbing_website.route')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('user_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='climbing_website.routegrade')),
            ],
        ),
        migrations.RunPython(create_admin_user)
    ]
