# Generated by Django 4.1.6 on 2023-03-02 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('climbing_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_done', to='climbing_website.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_done', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
