# Generated by Django 4.1.6 on 2023-03-13 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_website', '0002_routedone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Insolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='rock',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rocks', to='climbing_website.formation'),
        ),
        migrations.AlterField(
            model_name='rock',
            name='insolation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rocks', to='climbing_website.insolation'),
        ),
    ]
