# Generated by Django 4.1.6 on 2023-03-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_website', '0003_formation_insolation_alter_rock_formation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='autor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='number_of_glued',
            field=models.IntegerField(null=True),
        ),
    ]
