# Generated by Django 4.1.6 on 2023-03-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_website', '0004_alter_route_autor_alter_route_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='number_of_glued',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
