# Generated by Django 4.1.6 on 2023-03-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_website', '0005_alter_route_autor_alter_route_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
