# Generated by Django 4.1.6 on 2023-03-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_website', '0006_route_route_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='routereview',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='routereview',
            name='done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RouteDone',
        ),
    ]
