# Generated by Django 4.1.6 on 2023-03-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_website', '0009_routegrade_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routegrade',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
